# Generated by Django 6.0.7 on 2026-07-25 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Mahsulot nomi')),
                ('url', models.URLField(max_length=1000, verbose_name='Mahsulot havolasi')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Joriy narx')),
                ('update_interval', models.PositiveIntegerField(default=1440, verbose_name="Yangilanish oralig'i (daqiqada)")),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Kuzatuv statusi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilish sanasi")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilanish sanasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_products', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kuzatilayotgan mahsulot',
                'verbose_name_plural': 'Kuzatilayotgan mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Belgilangan narx')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Saqlash vaqti')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='tracker.trackedproduct', verbose_name='Hikoya')),
            ],
            options={
                'verbose_name': 'Narx hikoyasi',
                'verbose_name_plural': 'Narxlar hikoyasi',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
